### ISSUE TITLE
reproduce the results for CIFAR100

### ISSUE THREAD

**Issue by KyleZheng1997** [JiHooooo/SimMatch_cifar#1]
I just checked your code; it seems like you changed the DDP to DP, so the problem might either be in the data sampler or syncbn. Would you also like to share your training log ?

**Comment by KyleZheng1997** [comment]
Since I'm currently very busy with the AAAI submission, I might not have enough time to go through all the details of this codebase. However, I recommend simply changing DP back to DDP, which should be the easiest way to make everything work.  The dist_init function util/dist_init.py is the only function you to adapt the DDP to your local environments. You can find a quick introduction for DDP at https://pytorch.org/tutorials/intermediate/ddp_tutorial.html .

**Comment by JiHooooo** [comment]
The problem appears to be solved after I modified the ema function based on the implementation of TorchSSL. I will repeat the training process again and check whether it can reproduce the results for CIFAR100 in your paper. After that, i will try to adapt the DPP to my local environment. Anyway Thanks for your help and sharing your great work.
